FROM oven/bun:1
WORKDIR /app

COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile || bun install

COPY . .

ARG NEXT_PUBLIC_RECIPIENT_ADDRESS=""
ARG NEXT_PUBLIC_ALIEN_RECIPIENT_ADDRESS=""
ENV NEXT_PUBLIC_RECIPIENT_ADDRESS=$NEXT_PUBLIC_RECIPIENT_ADDRESS
ENV NEXT_PUBLIC_ALIEN_RECIPIENT_ADDRESS=$NEXT_PUBLIC_ALIEN_RECIPIENT_ADDRESS
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

RUN bun run build

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["bun", "run", "start"]
